### ISSUE TITLE
City not found error at boot time

### ISSUE THREAD

**Issue by aldweb** [PierroD/TinyWeather#1]
Hello,
Your little piece of software is great, thanks :-)

I am usually not yet connected to the internet when my old laggy laptop boots.
Then, if I set up TinyWeather to launch at boot time, I get this error message:
![image](https://user-images.githubusercontent.com/61916846/84591555-9e495480-ae3f-11ea-9470-349a1c0963f9.png)
The error window prompts again every few seconds, on top of the previous error windows.

Keep up the good work!
aldweb

**Comment by PierroD** [comment]
Thank you for your repport, this error has been fixed. You can now upgrade TinyWeather to the lastest version.
Commit : https://github.com/PierroD/TinyWeather/commit/c33691843fde968e2f5adb450d12903fdfb5ce22 
fixe : #1

**Comment by aldweb** [comment]
Thank you for fixing the bug.
I just downloaded the new version and it seems to work fine.
Great!
aldweb

**Comment by aldweb** [comment]
Hello again.
The same error appeared again, some time ago.
And, if I look for a city, like "Paris", I get this message: "Paris doesn't exist inside our database or in real life".
I would really appreciate if you could fix it as I love your software :-)
